apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  namespace: openshift-logging
  name: logging-loki
spec:
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
      - version: v13
        effectiveDate: 2023-10-15
    secret:
      name: minio-test
      type: s3
  storageClassName: crc-csi-hostpath-provisioner
  tenants:
    mode: openshift-logging
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-test
  namespace: openshift-logging
stringData:
  endpoint: http://minio.minio.svc:9000
  bucketnames: tempo
  access_key_id: tempo
  access_key_secret: supersecret
type: Opaque
---
# Workaround for CRC to be able to query data
# on a normal OCP cluster admin user is kube-admin which LokiStack expects, therefore this workaround.
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cluster-admin
users:
  - kubeadmin
---