apiVersion: v1
kind: Namespace
metadata:
  name: ploffay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-logs-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-collector-logs-writer
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: openshift-logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cabundle
  namespace: openshift-logging
  annotations:
    "service.beta.openshift.io/inject-cabundle": "true"
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: openshift-logging
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.102.1
  volumeMounts:
    - name: cabundle-volume
      mountPath: /etc/pki/ca-trust/source/service-ca
      readOnly: true
  volumes:
    - name: cabundle-volume
      configMap:
        name: cabundle
  config:
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      resource:
        attributes:
          - key: log_type
            value: application
            action: upsert
          - key: collector_type
            value: otel
            action: upsert
          - key: loki.resource.labels
            value: collector_type, log_type
            action: insert
      attributes:
        actions:
          - key: log_type
            value: application
            action: upsert
          - key: collector_type
            value: otel
            action: upsert
          - key: kubernetes_namespace_name
            value: tutorial-application
            action: upsert
          - key: loki.attribute.labels
            value: collector_type, log_type
            action: insert

    exporters:
      loki:
        endpoint: https://lokistack-dev-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/application/loki/api/v1/push
        default_labels_enabled:
          exporter: false
          job: true
        headers:
          "X-Scope-OrgID": application
        tls:
#          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
#          server_name_override: "lokistack-dev-gateway-http.openshift-logging.svc.cluster.local"
#          insecure_skip_verify: true
        auth:
          authenticator: bearertokenauth
      debug:
        verbosity: detailed

    service:
      telemetry:
        logs:
          level: debug
      extensions: [bearertokenauth]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [attributes, resource]
          exporters: [debug,loki]