apiVersion: v1
kind: Namespace
metadata:
  name: ploffay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-logs-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-collector-logs-writer
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: ploffay
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cabundle
  annotations:
    "service.beta.openshift.io/inject-cabundle": "true"
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.103.0
  volumeMounts:
    - name: cabundle-volume
      mountPath: /etc/pki/ca-trust/source/service-ca
      readOnly: true
  volumes:
    - name: cabundle-volume
      configMap:
        name: cabundle
  config:
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      loki:
        endpoint: https://lokistack-dev-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/application/loki/api/v1/push
        default_labels_enabled:
          exporter: false
          job: true
        headers:
          "X-Scope-OrgID": application
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
#          server_name_override: "lokistack-dev-gateway-http.openshift-logging.svc.cluster.local"
#          insecure_skip_verify: true
        auth:
          authenticator: bearertokenauth
      debug: {}

    service:
      telemetry:
        logs:
          level: debug
      extensions: [bearertokenauth]
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters: [debug,loki]