apiVersion: v1
kind: Namespace
metadata:
  name: ploffay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-logs-writer
rules:
 - apiGroups:
   - loki.grafana.com
   resourceNames:
   - logs
   resources:
   - application
   - audit
   - infrastructure
   verbs:
   - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-logs-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-logs-writer
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: openshift-logging
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: openshift-logging
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.103.0
  volumeMounts:
    - name: cabundle-volume
      mountPath: /etc/pki/ca-trust/source/service-ca
      readOnly: true
  volumes:
    - name: cabundle-volume
      configMap:
        name: cabundle
  config:
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      resource:
        attributes:
          - key: collector_type
            value: otel
            action: insert
          - key: loki.format
            action: insert
            value: json
          - key:  kubernetes_namespace_name
            from_attribute: k8s.namespace.name
            action: upsert
          - key:  kubernetes_pod_name
            from_attribute: k8s.pod.name
            action: upsert
          - key: kubernetes_container_name
            from_attribute: k8s.container.name
            action: upsert
          - key: log_type
            value: application
            action: upsert
          - key: loki.resource.labels
            value: log_type, kubernetes_namespace_name, kubernetes_pod_name, kubernetes_container_name, collector_type
            action: insert
      attributes:
        actions:
          - key: loki.attribute.labels
            value: level
            action: insert
      transform:
        log_statements:
          - context: resource
          - context: log
            statements:
              - set(attributes["level"], ConvertCase(severity_text, "lower"))

    exporters:
      loki:
        endpoint: https://lokistack-dev-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/application/loki/api/v1/push
        default_labels_enabled:
          exporter: true
          job: true
        headers:
          "X-Scope-OrgID": application
        tls:
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
#          server_name_override: "lokistack-dev-gateway-http.openshift-logging.svc.cluster.local"
#          insecure_skip_verify: true
        auth:
          authenticator: bearertokenauth
      debug:
        verbosity: detailed

    service:
      telemetry:
        logs:
          level: debug
      extensions: [bearertokenauth]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [transform, resource]
          exporters: [debug,loki]